sudo: false
language: C
services:
  - docker

cache:
    directories:
      - $HOME/.cache

env:
    global:
      - PRODUCT=tarantool-stat
    matrix:
      - TARGET=test VERSION=1_7
      - TARGET=test VERSION=2_2
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=28
      - OS=fedora DIST=29
      - OS=fedora DIST=30
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
      - OS=ubuntu DIST=cosmic
      - OS=ubuntu DIST=disco
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster

script:
  - git describe --long
  - |
    if [ "${TARGET}" = "test" ]; then
        ./tests/setup.sh;
        ./tests/run_all.sh;
    else
        git clone https://github.com/packpack/packpack.git packpack;
        packpack/packpack;
    fi;

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: tarantool
    repository: "1_7"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "1_9"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email:
    recipients: []
      # - build@tarantool.org
    on_success: change
    on_failure: always
